### ISSUE TITLE
got just a black picture

### ISSUE THREAD

**Issue by Bra1nsen** [19tchoubou/CloudSegmentation#2]
bro can I get your e mail, iam trying your code, but i only get a black pic..

I would be very grateful for your help!

**Comment by 19tchoubou** [comment]
Could you please provide the code you used ?
Copying/pasting the snippet in the README.md, the image I get (using `matplotlib.pyplot.imshow(segmented_image)` for instance) is working fine for me, even in a whole new environment.

**Comment by Bra1nsen** [comment]
yea sure! nice that youre active.

import numpy as np
from segmenter import Segmenter
from PIL import Image

image_to_segment = np.array(Image.open('data/fisheye.jpg'))/255
segmenter = Segmenter()

segmented_image = segmenter.segment(image_to_segment, radius = 140)
np.set_printoptions(threshold=np.inf)
print(type(segmented_image))
print(segmented_image)

array = np.reshape(segmented_image, (312,312))
data = Image.fromarray(array)
data.save('segmented.png')

**Comment by 19tchoubou** [comment]
import numpy as np
    from segmenter import Segmenter
    from PIL import Image
    import matplotlib.pyplot as plt
    
    image_to_segment = np.array(Image.open('data/fisheye.jpg'))/255
    segmenter = Segmenter()
    
    segmented_image = segmenter.segment(image_to_segment, radius=140)
    plt.imsave('segmented.png', segmented_image)

This snippet should work as you want. 
The segmenter is working properly, but by default the resulting array values are integers within the range 0 to 3 (so 4 values, corresponding to background, sky, clouds, and sun). Pillow doesn't seem to handle that format properly (my guess is that it expects integers in the range (0, 255). So when it is provided input within the range (0,3) it is relatively very small and it appears dark. But haven't looked it up).
Fortunately, pyplot adopts a better mapping in our case.

**Comment by Bra1nsen** [comment]
Thank you! Your snippet worked. That was the result: ![segmented](https://user-images.githubusercontent.com/58213050/145689735-6988acef-2c88-4c83-84b8-975abc33d49d.png)

**Comment by 19tchoubou** [comment]
Glad to help!
