### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by Bra1nsen** [19tchoubou/CloudSegmentation#3]
Hey please excuse me for asking so much.
How come you wrote some code for cloud detection - are you working in that direction?

I have also just successfully tested the code on my own images. I have now scrolled through your file more often, is there a way to change the colors?

**Comment by 19tchoubou** [comment]
Glad to hear that!

Matplotlib.pyplot.imsave has a cmap parameter through which you can change colors as follows:
`plt.imsave('segmented_image.png', segmented_image, cmap='plasma')`
You can easily find a list of values that param can take online.

I am not working in cloud detection, but worked on a data science project that needed cloud detection some time ago.
